apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: galaxy-tools-maker-pvc
  namespace: galaxy2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-client
