apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: galaxy-tools-maker
  name: galaxy-tools-maker-svc
  namespace: galaxy2
spec:
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30009
  selector:
    k8s-app: galaxy-tools-maker
  type: NodePort
